#
# https://sites.google.com/a/cgspeed.com/cgspeed/motion-capture
#
from typing import Dict
from ...humanoid_bones import HumanoidBone

MAP: Dict[str, HumanoidBone] = {
    'hip': HumanoidBone.hips,
    'abdomen': HumanoidBone.spine,
    'chest': HumanoidBone.chest,
    'neck': HumanoidBone.neck,
    'head': HumanoidBone.head,
    'leftEye': HumanoidBone.leftEye,
    'rightEye': HumanoidBone.rightEye,
    'rCollar': HumanoidBone.rightShoulder,
    'rShldr': HumanoidBone.rightUpperArm,
    'rForeArm': HumanoidBone.rightLowerArm,
    'rHand': HumanoidBone.rightHand,
    'rThumb1': HumanoidBone.rightThumbProximal,
    'rThumb2': HumanoidBone.rightThumbIntermediate,
    'rIndex1': HumanoidBone.rightIndexProximal,
    'rIndex2': HumanoidBone.rightIndexIntermediate,
    'rMid1': HumanoidBone.rightMiddleProximal,
    'rMid2': HumanoidBone.rightMiddleIntermediate,
    'rRing1': HumanoidBone.rightRingProximal,
    'rRing2': HumanoidBone.rightRingIntermediate,
    'rPinky1': HumanoidBone.rightLittleProximal,
    'rPinky2': HumanoidBone.rightLittleIntermediate,
    'lCollar': HumanoidBone.leftShoulder,
    'lShldr': HumanoidBone.leftUpperArm,
    'lForeArm': HumanoidBone.leftLowerArm,
    'lHand': HumanoidBone.leftHand,
    'lThumb1': HumanoidBone.leftThumbProximal,
    'lThumb2': HumanoidBone.leftThumbIntermediate,
    'lIndex1': HumanoidBone.leftIndexProximal,
    'lIndex2': HumanoidBone.leftIndexIntermediate,
    'lMid1': HumanoidBone.leftMiddleProximal,
    'lMid2': HumanoidBone.leftMiddleIntermediate,
    'lRing1': HumanoidBone.leftRingProximal,
    'lRing2': HumanoidBone.leftRingIntermediate,
    'lPinky1': HumanoidBone.leftLittleProximal,
    'lPinky2': HumanoidBone.leftLittleIntermediate,
    # 'rButtock': HumanoidBone,
    'rThigh': HumanoidBone.rightUpperLeg,
    'rShin': HumanoidBone.rightLowerLeg,
    'rFoot': HumanoidBone.rightFoot,
    # 'lButtock': HumanoidBone,
    'lThigh': HumanoidBone.leftUpperLeg,
    'lShin': HumanoidBone.leftLowerLeg,
    'lFoot': HumanoidBone.leftFoot,
}
